PRODUCT_ID := a3003ns
CLASS_ID:=iptime

CPU_NAME:=mt7621
WIFI_2G:=mt7603e
WIFI_5G:=mt7612e
DRAM_SIZE:=128m

EXTERNAL_SWITCH:=y
HW_NAT:=y
FLASH_SIZE:=0x1000000
EEPROM_FILE:=IP04317B_2.4G_12.15_OK.bin
EEPROM_FILE_5G:=IP04317B_5G_12.15_OK.bin
BOOT_FILENAME:=uboot.bin.mt7621.128m.llllw
USE_FACTORY_SECTION:=y
LOAD_ADDRESS := 80001000
SQUASHCMD:=./mksquash
SQUASHCMD_COMP:=xz
NO_PADDING_FOR_ROOTFS:=y
LANG_PACKS:=kr,en

PRODUCT_TAG:=$(CPU_NAME).$(WIFI_2G).$(WIFI_5G).$(DRAM_SIZE)$(if $(OPTION_TAG),.$(OPTION_TAG))
KERNEL_FILENAME:=vmlinux.$(PRODUCT_TAG)
KCONFIG_FILE_NAME:=config.$(PRODUCT_TAG)
MODULE_DIR:=$(PRODUCT_TAG)
TNTFS_MODULE_NAME:=tntfs.ko.$(PRODUCT_TAG)

SDK_VERSION:=SDK_4320
KERNEL_PATH:=../../linux
PREMAKE_TARGET_NAME:=$(WIFI_2G) $(WIFI_5G)

